### ISSUE TITLE
[manfred2HTML] Create new CV template monocrome example

### ISSUE THREAD

**Issue by juanpms2** [Lemoncode/manfred-export-app#249]
This template only use this colors:
- light-50 color
- info-50 color 
- Primary palete color variants

![CV-monocrome-desktop](https://github.com/Lemoncode/manfred-export-app/assets/58438522/fd3fffe3-decd-4d3f-ba42-61c8e068f8f8)

This is an example or guide for the user image:

```html
    <div class="avatar">
      <div class="image"></div>
      <div class="filter"></div>
    </div>
```
```css
.avatar {
  position: relative;
  width: 300px;
  height: 300px;
  overflow: hidden;
}

.image {
  width: 100%;
  height: 100%;
  background-image: url("https://media-asgard.s3.eu-west-1.amazonaws.com/22/11/22/46a1d99e-54b1-4d4f-b887-bd32b97684d8_david_squared_2018.jpg");
  background-size: cover;
  filter: saturate(25%);
}

.filter {
  position: absolute;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background-color: #28868b; /* primary-500 color */
  opacity: 0.15;
}
```
